# Generated by Django 2.2 on 2019-04-30 16:51

import appsDatabase.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='AppsDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('website', models.URLField(max_length=255, verbose_name='website')),
                ('launchYear', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), appsDatabase.models.max_value_current_year], verbose_name='year_launched')),
                ('serviceType', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('C2C', 'C2C'), ('P2C', 'P2C'), ('P2P', 'P2P'), ('P2B', 'P2B')], default='B2C', max_length=3)),
                ('businessModel', models.CharField(choices=[('Freemium', 'Freemium'), ('SaaS', 'SaaS'), ('PaaS', 'PaaS')], default='SAAS', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('monitization', models.TextField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('tags', models.ManyToManyField(to='appsDatabase.Tags')),
            ],
        ),
    ]
