# Generated by Django 2.2 on 2019-04-30 16:53

from django.db import migrations


def create_data(apps, schema_editor):
    AppsDatabase = apps.get_model('appsDatabase', 'AppsDatabase')
    AppsDatabase(name="App 001",
                 website="www.google.com",
                 launchYear="2015",
                 serviceType="B2C",
                 businessModel="SAAS",
                 description="App 001 description",
                 monitization="App 001 Monitization strategy",
                 ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('appsDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
